/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHERegisAirdropInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "encryptedEmailOf"
      | "getTotalRegistered"
      | "hasRegistered"
      | "protocolId"
      | "registerEmail"
      | "totalRegistered"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "encryptedEmailOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerEmail",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRegistered",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "encryptedEmailOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEmail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRegistered",
    data: BytesLike
  ): Result;
}

export interface FHERegisAirdrop extends BaseContract {
  connect(runner?: ContractRunner | null): FHERegisAirdrop;
  waitForDeployment(): Promise<this>;

  interface: FHERegisAirdropInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encryptedEmailOf: TypedContractMethod<[user: AddressLike], [string], "view">;

  getTotalRegistered: TypedContractMethod<[], [bigint], "view">;

  hasRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerEmail: TypedContractMethod<
    [encryptedEmail: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;

  totalRegistered: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encryptedEmailOf"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalRegistered"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerEmail"
  ): TypedContractMethod<
    [encryptedEmail: BytesLike, zkProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalRegistered"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
